# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
        - "5432:5432"
    env_file:
      - database.env # configure postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/ # persist data even if container shuts down
    networks:
      - dmg_admin

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    networks:
      - dmg_admin
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.16.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200/
    networks:
      - dmg_admin
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  dmg_admin:

volumes:
  postgres-data:
#  data01: # named volumes can be managed easier using docker-compose

